name: Docker Image CI
# 触发条件：当master branch触发push（push，merge Pull Request）时，弱docker文件夹下的文件有更新，则触发。
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dockerfile
        uses: actions/checkout@v2

      - name: Login to Ali Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
          username: ${{ secrets.ALI_DOCKER_HUB_USN }}
          password: ${{ secrets.ALI_DOCKER_HUB_PWD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.cn-shenzhen.aliyuncs.com/jsdawn/funny-express:v2
      # 使用Aliyun操作指南提供的命令
      # - name: Push to Ali Docker Repository
      #   run: |
      #     docker login -u ${{ secrets.ALI_DOCKER_HUB_USN }} -p ${{ secrets.ALI_DOCKER_HUB_PWD }} ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
      #     docker build -t registry.cn-shenzhen.aliyuncs.com/jsdawn/funny-express:v1 .
      #     docker push registry.cn-shenzhen.aliyuncs.com/jsdawn/funny-express:v1
